//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.DetailRoomBills = new HashSet<DetailRoomBill>();
            this.DetailTicketBills = new HashSet<DetailTicketBill>();
        }
    
        public int Bill_id { get; set; }
        public Nullable<System.DateTime> Bill_date { get; set; }
        public Nullable<int> Bill_type { get; set; }
        public Nullable<int> Bill_total { get; set; }
        public Nullable<int> ID_voucher { get; set; }
        public Nullable<int> ID_Payment { get; set; }
        public string Status { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual Voucher Voucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailRoomBill> DetailRoomBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailTicketBill> DetailTicketBills { get; set; }
    }
}
