//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatReply
    {
        public int Reply_ID { get; set; }
        public string Text_Reply { get; set; }
        public Nullable<int> CCM_ID { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
    
        public virtual ChatComment ChatComment { get; set; }
    }
}
