//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID_Comment { get; set; }
        public Nullable<int> Ticket_id { get; set; }
        public string Username { get; set; }
        public string Content { get; set; }
        public Nullable<int> Room_number { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
