//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNTravel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webtraveldbEntities : DbContext
    {
        public webtraveldbEntities()
            : base("name=webtraveldbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accompany> Accompanies { get; set; }
        public virtual DbSet<Accompany_Type> Accompany_Type { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<ChatComment> ChatComments { get; set; }
        public virtual DbSet<ChatReply> ChatReplies { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DetailContract> DetailContracts { get; set; }
        public virtual DbSet<DetailRoomBill> DetailRoomBills { get; set; }
        public virtual DbSet<DetailTicketBill> DetailTicketBills { get; set; }
        public virtual DbSet<ListFavourite> ListFavourites { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Revenue> Revenues { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Room_Type> Room_Type { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<TravelService> TravelServices { get; set; }
        public virtual DbSet<VNTravel> VNTravels { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
    }
}
