//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailTicketBill
    {
        public int Customer_id { get; set; }
        public int Ticket_id { get; set; }
        public int ID_service { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int Bill_id { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual TravelService TravelService { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
