//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailContract
    {
        public int ID_Contract { get; set; }
        public int Admin_id { get; set; }
        public int Accompany_ID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Terms { get; set; }
        public Nullable<int> Price { get; set; }
        public int ID_Payment { get; set; }
        public Nullable<double> Contract_percent { get; set; }
        public Nullable<int> Contract_status { get; set; }
    
        public virtual Accompany Accompany { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual VNTravel VNTravel { get; set; }
    }
}
