//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListFavourite
    {
        public int ID_favourite { get; set; }
        public string Username { get; set; }
        public Nullable<int> Room_number { get; set; }
        public Nullable<int> Ticket_id { get; set; }
        public Nullable<int> Id_service { get; set; }
        public Nullable<bool> status_fav { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Room Room { get; set; }
        public virtual TravelService TravelService { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
