//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Comments = new HashSet<Comment>();
            this.DetailRoomBills = new HashSet<DetailRoomBill>();
            this.ListFavourites = new HashSet<ListFavourite>();
        }
    
        public int Room_number { get; set; }
        public Nullable<int> Room_status { get; set; }
        public Nullable<int> Room_type { get; set; }
        public Nullable<int> Accompany_id { get; set; }
        public string Room_image { get; set; }
        public Nullable<int> Room_Quantily { get; set; }
        public string Location { get; set; }
    
        public virtual Accompany Accompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailRoomBill> DetailRoomBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListFavourite> ListFavourites { get; set; }
        public virtual Room_Type Room_Type1 { get; set; }
    }
}
