//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Comments = new HashSet<Comment>();
            this.DetailTicketBills = new HashSet<DetailTicketBill>();
            this.ListFavourites = new HashSet<ListFavourite>();
        }
    
        public int Ticket_id { get; set; }
        public string Ticket_name { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ID_price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Flight_Number { get; set; }
        public Nullable<int> Accompany_ID { get; set; }
        public string Ticket_image { get; set; }
        public Nullable<int> Ticket_Status { get; set; }
        public string Departure { get; set; }
        public string destination { get; set; }
    
        public virtual Accompany Accompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailTicketBill> DetailTicketBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListFavourite> ListFavourites { get; set; }
        public virtual Price Price { get; set; }
    }
}
