//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelService()
        {
            this.DetailRoomBills = new HashSet<DetailRoomBill>();
            this.DetailTicketBills = new HashSet<DetailTicketBill>();
            this.ListFavourites = new HashSet<ListFavourite>();
        }
    
        public int ID_service { get; set; }
        public string serviceName { get; set; }
        public Nullable<int> ID_service_type { get; set; }
        public Nullable<int> Accompany_ID { get; set; }
        public Nullable<int> Service_Status { get; set; }
    
        public virtual Accompany Accompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailRoomBill> DetailRoomBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailTicketBill> DetailTicketBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListFavourite> ListFavourites { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        public bool IsSelected { get; internal set; }
    }
}
